PartnerApp.add_image 'http://s3-p.animoto.com/Image/maYvpK03IYvnihGuB0YkAg/l.jpg'
PartnerApp.add_image 'http://s3-p.animoto.com/Image/1bROwNFCqptsf2tYovp11g/l.jpg'
PartnerApp.add_image 'http://s3-p.animoto.com/Image/Pvny15tMg8w027iAx52ZFw/l.jpg'
PartnerApp.add_image 'http://s3-p.animoto.com/Image/a7PLsMNvwKTiphwFQTZSBQ/l.jpg'
PartnerApp.add_image 'http://s3-p.animoto.com/Image/47VqIpXpoEmoK3yB0MPM1Q/l.jpg'
